#!/usr/bin/env python3
"""Generate the dependency-free rooted MSC+JC69 C++ evaluator."""

from __future__ import annotations

from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from global_theta_jc69_quartet.annotated_species_tree import (
    iter_nodes_postorder,
)
from global_theta_jc69_quartet.quartet_site_pattern_probability import (
    QuartetSitePatternProbabilityEngine,
)
from global_theta_jc69_quartet.quartet_theta_estimator import (
    THETA_SYMBOL,
    parse_quartet_topology,
)


PATTERNS = (
    "AAAA", "AAAC", "AACA", "AACC", "AACG",
    "ACAA", "ACAC", "ACAG", "ACCA", "ACCC",
    "ACCG", "ACGA", "ACGC", "ACGG", "ACGT",
)

UNBALANCED_TOPOLOGY = "(((A,B),C),D);"


def cpp(expr: sp.Expr) -> str:
    return sp.cxxcode(expr, standard="c++17")


def evaluator(name: str, topology: str) -> list[str]:
    tree = parse_quartet_topology(topology)
    all_clades = [
        node.clade for node in iter_nodes_postorder(tree.root)
    ]
    engine = QuartetSitePatternProbabilityEngine(
        tree,
        model_name="JC69",
        ne_override_by_clade={
            clade: THETA_SYMBOL / 4 for clade in all_clades
        },
        mu_override_by_clade={clade: 1 for clade in all_clades},
        external_symbols=(THETA_SYMBOL,),
    )
    expressions = [
        sp.powsimp(
            engine.canonical_probability_expression(pattern),
            combine="exp",
            force=True,
        )
        for pattern in PATTERNS
    ]
    replacements, reduced = sp.cse(
        expressions,
        symbols=sp.numbered_symbols("x"),
        optimizations="basic",
        order="canonical",
    )

    lines = [
        f"inline std::array<long double, 15> {name}(",
        "    long double s1, long double s2, long double s3,",
        "    long double theta) noexcept {",
    ]
    for symbol, expression in replacements:
        lines.append(
            f"    const long double {symbol} = {cpp(expression)};"
        )
    lines.append("    return {{")
    for index, expression in enumerate(reduced):
        comma = "," if index + 1 < len(reduced) else ""
        lines.append(f"        {cpp(expression)}{comma}")
    lines.extend(["    }};", "}", ""])
    print(
        f"{name}: {len(replacements)} common subexpressions",
        file=sys.stderr,
    )
    return lines


def triplet_evaluator() -> list[str]:
    return [
        "inline std::array<long double, 5> triplet(",
        "    long double s1, long double s2, long double theta",
        ") noexcept {",
        "    // Marginalize D from (((A,B),C),D). Sampling consistency",
        "    // removes the arbitrary older age; s3=s2+theta is only a",
        "    // numerically convenient representative of that marginal.",
        "    const auto quartet = unbalanced(s1, s2, s2 + theta, theta);",
        "    return {{",
        "        quartet[0] + 3 * quartet[1],",
        "        quartet[2] + quartet[3] + 2 * quartet[4],",
        "        quartet[5] + quartet[6] + 2 * quartet[7],",
        "        quartet[8] + quartet[9] + 2 * quartet[10],",
        "        quartet[11] + quartet[12] + quartet[13] + quartet[14]",
        "    }};",
        "}",
        "",
    ]


def main() -> None:
    output = ROOT.parent / "src" / "jc69_msc_probabilities.hpp"
    lines = [
        "#ifndef JC69_MSC_PROBABILITIES_HPP",
        "#define JC69_MSC_PROBABILITIES_HPP",
        "",
        "#include <array>",
        "#include <cmath>",
        "",
        "namespace branch_length::jc69_msc {",
        "",
        "// Generated by branch_length_global_theta_jc69/"
        "generate_cpp_probabilities.py.",
        "// s1,s2,s3 are rooted species divergence ages in SU;",
        "// theta=4*Ne*mu. Quartet positions are A,B,C,D; triplet",
        "// positions are A,B,C. Positional order is never permuted.",
        "",
    ]
    lines.extend(evaluator("unbalanced", UNBALANCED_TOPOLOGY))
    lines.extend(triplet_evaluator())
    lines.extend([
        "} // namespace branch_length::jc69_msc",
        "",
        "#endif",
        "",
    ])
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
