#!/usr/bin/env python3
"""Generate the dependency-free C++ MSC+JC69 quartet probability evaluator."""

from __future__ import annotations

from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from global_theta_jc69_quartet.annotated_species_tree import iter_nodes_postorder
from global_theta_jc69_quartet.quartet_site_pattern_probability import (
    QuartetSitePatternProbabilityEngine,
)
from global_theta_jc69_quartet.quartet_theta_estimator import parse_quartet_topology


PATTERNS = (
    "AAAA", "AAAC", "AACA", "AACC", "AACG",
    "ACAA", "ACAC", "ACAG", "ACCA", "ACCC",
    "ACCG", "ACGA", "ACGC", "ACGG", "ACGT",
)


def cpp(expr: sp.Expr) -> str:
    return sp.cxxcode(expr, standard="c++17").replace("std::pow", "std::pow").replace("std::exp", "std::exp")


def main() -> None:
    tree = parse_quartet_topology("((A,B),(C,D));")
    clades = {
        tuple(sorted(node.clade)): node.clade
        for node in iter_nodes_postorder(tree.root)
    }
    a, b, c, d, t, theta = sp.symbols("a b c d t theta", positive=True)

    # Fix the two cherry ages to 1 and the root age to 2. Branch-specific
    # mutation rates then make a,b,c,d the four pendant SU lengths and split
    # the unrooted focal SU length t evenly around the arbitrary root. Setting
    # Ne=theta/(4*mu) preserves one theta=4*Ne*mu on every species branch.
    mu = {
        clades[("A",)]: a,
        clades[("B",)]: b,
        clades[("C",)]: c,
        clades[("D",)]: d,
        clades[("A", "B")]: t / 2,
        clades[("C", "D")]: t / 2,
        clades[("A", "B", "C", "D")]: sp.Integer(1),
    }
    ne = {clade: theta / (4 * rate) for clade, rate in mu.items()}
    engine = QuartetSitePatternProbabilityEngine(
        tree,
        ne_override_by_clade=ne,
        mu_override_by_clade=mu,
        external_symbols=(a, b, c, d, t, theta),
    )
    age_values = dict(zip(engine.age_symbols, (1, 1, 2)))
    expressions = [
        sp.factor_terms(sp.expand(engine.canonical_probability_expression(pattern).subs(age_values)))
        for pattern in PATTERNS
    ]
    replacements, reduced = sp.cse(
        expressions,
        symbols=sp.numbered_symbols("x"),
        optimizations="basic",
        order="canonical",
    )

    output = ROOT.parent / "src" / "jc69_msc_probabilities.hpp"
    lines = [
        "#ifndef JC69_MSC_PROBABILITIES_HPP",
        "#define JC69_MSC_PROBABILITIES_HPP",
        "",
        "#include <array>",
        "#include <cmath>",
        "",
        "namespace branch_length::jc69_msc {",
        "",
        "// Generated by branch_length_global_theta_jc69/generate_cpp_probabilities.py.",
        "// Arguments a,b,c,d,t are substitution-unit lengths; theta=4*Ne*mu.",
        "inline std::array<long double, 15> probabilities(",
        "    long double a, long double b, long double c, long double d,",
        "    long double t, long double theta) noexcept {",
    ]
    for symbol, expression in replacements:
        lines.append(f"    const long double {symbol} = {cpp(expression)};")
    lines.append("    return {{")
    for index, expression in enumerate(reduced):
        comma = "," if index + 1 < len(reduced) else ""
        lines.append(f"        {cpp(expression)}{comma}")
    lines.extend([
        "    }};",
        "}",
        "",
        "} // namespace branch_length::jc69_msc",
        "",
        "#endif",
        "",
    ])
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {output} with {len(replacements)} common subexpressions.")


if __name__ == "__main__":
    main()
